[package]
name = "xfparser"
version = "0.1.0"
edition = "2021"
description = "intuitive parser api and tooling"
license = "MIT"

[dependencies]
bytestring = "1.4.0"
derive-getters = "0.5.0"
indexmap = "2.7.0"
thiserror = "2.0.7"
